sudo: required
dist: trusty
language: node_js
node_js:
  - node

before_install:
  - export CHROME_BIN=/usr/bin/google-chrome
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
services:
  - postgresql

before_script:
  - npm install istanbul
  - npm install -g istanbul
  - mkdir coverage
  - psql -c 'drop database if exists doc_api_test;' -U postgres
  - psql -c 'create database doc_api_test;' -U postgres
  - NODE_ENV=test npm run migrate
  
script:
  - npm run coverage

addons:
  postgresql: "9.3"

after_failure:
  - npm run coverage
 
